# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Qpay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Qpay
pod 'Plaid'
pod 'Firebase/Auth'
end
